/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    VITE_NEXT_PUBLIC_API_BASE_URL: process.env.VITE_NEXT_PUBLIC_API_BASE_URL,
    VITE_NEXT_PUBLIC_API_AUTH_URL: process.env.VITE_NEXT_PUBLIC_API_AUTH_URL,
    VITE_NEXT_PUBLIC_API_ME_URL: process.env.VITE_NEXT_PUBLIC_API_ME_URL,
    VITE_NEXT_PUBLIC_API_CLIENTES_URL: process.env.VITE_NEXT_PUBLIC_API_CLIENTES_URL,
    VITE_NEXT_PUBLIC_API_UNIDADES_URL: process.env.VITE_NEXT_PUBLIC_API_UNIDADES_URL,
    VITE_NEXT_PUBLIC_API_SERVICOS_URL: process.env.VITE_NEXT_PUBLIC_API_SERVICOS_URL,
    VITE_NEXT_PUBLIC_API_CONFORMIDADE_URL: process.env.VITE_NEXT_PUBLIC_API_CONFORMIDADE_URL,
  },
};

export default nextConfig;